function C = cohorts(id)
%COHORTS  Configuration for each experimental cohort modeled in the paper.
%
%   C = COHORTS(id) returns the configuration struct for one cohort.
%   COHORTS (no arguments) lists the available cohort ids.
%
%   Cohorts (all modeled on Session 1 of the odor-based 2AFC task):
%     TSC_M_det    - Tsc2 males,     deterministic reward schedule (Fig 2)
%     TSC_F_det    - Tsc2 females,   deterministic reward schedule (Fig 2)
%     Shank_M_det  - Shank3B males,  deterministic reward schedule (Fig 3)
%     Shank_F_det  - Shank3B females,deterministic reward schedule (Fig 3)
%     TSC_M_prob   - Tsc2 males,     probabilistic reward schedule (Fig 4)
%     Shank_M_prob - Shank3B males,  probabilistic reward schedule (Fig 4)
%
%   Fields:
%     dataFile      processed Session-1 behavior table (data/processed)
%     fitFile       model-fit results file             (results)
%     pEngagedFile  p(engaged) trajectories file       (results), '' if none
%     models        candidate models, in the order they are fitted
%     groupScheme   'two'   : genotype 1 = Het, else WT
%                   'three' : genotype 2 = KO, 1 = Het, else WT
%     pReward       reward probability of a correct choice passed to the
%                   generative model during validation simulations
%                   (1 = deterministic, 0.9 = probabilistic).
%                   [] = call the generative model without a pReward
%                   argument (the convention for the Shank3B deterministic
%                   cohorts; equivalent to pReward = 1 except for random
%                   number stream consumption).
%     pEngaged      whether validate_models saves p(engaged) trajectories
%     indivSubplots subplot grid for individual validation curves
%     inequalityConstraints - whether fits pass an (inert) Aineq/bineq
%                   constraint set to fmincon (probabilistic cohorts)
%
%   See also MODEL_SPECS, FIT_MODELS, COMPARE_PARAMS, VALIDATE_MODELS.

%   Author: Jing-Jing Li (jl3676@berkeley.edu)

if nargin == 0
    disp({'TSC_M_det'; 'TSC_F_det'; 'Shank_M_det'; 'Shank_F_det'; 'TSC_M_prob'; 'Shank_M_prob'});
    return
end

% Candidate model sets (fitting order matters: a0b3s must precede
% a0b3s_hybrid, whose starting values are initialized from a0b3s fits).
MODELS_5 = {'RL_epsilon', 'a0b3s', 'a0b3s_hybrid', 'a0b2s_hybrid', 'a0b1s_hybrid'};
MODELS_6 = [MODELS_5, {'a01s_hybrid'}];
MODELS_8 = [MODELS_6, {'Aab1s_hybrid', 'b1s_hybrid'}];

switch id
    case 'TSC_M_det'    % Tsc2 males, deterministic schedule
        C = struct( ...
            'dataFile',     'TSC2_AB_D1.mat', ...
            'fitFile',      'FitModels_TSC_sess1.mat', ...
            'pEngagedFile', 'p_engaged_TSC.mat', ...
            'models',       {MODELS_6}, ...
            'groupScheme',  'two', ...
            'pReward',      1, ...
            'pEngaged',     true, ...
            'indivSubplots', [6 5], ...
            'inequalityConstraints', false);

    case 'TSC_F_det'    % Tsc2 females, deterministic schedule
        C = struct( ...
            'dataFile',     'TSC2_F_AB_D1.mat', ...
            'fitFile',      'FitModels_TSC_F_sess1.mat', ...
            'pEngagedFile', 'p_engaged_TSC_F.mat', ...
            'models',       {MODELS_5}, ...
            'groupScheme',  'two', ...
            'pReward',      1, ...
            'pEngaged',     true, ...
            'indivSubplots', [6 5], ...
            'inequalityConstraints', false);

    case 'Shank_M_det'  % Shank3B males (WT/Het/KO), deterministic schedule
        % NOTE: the a01s_hybrid model is included to match the fit results
        % archived in results/FitModels_Shank_sess1.mat.
        C = struct( ...
            'dataFile',     'Shank3B_M_AB_D1.mat', ...
            'fitFile',      'FitModels_Shank_sess1.mat', ...
            'pEngagedFile', 'p_engaged_shank.mat', ...
            'models',       {MODELS_6}, ...
            'groupScheme',  'three', ...
            'pReward',      [], ...
            'pEngaged',     true, ...
            'indivSubplots', [8 5], ...
            'inequalityConstraints', false);

    case 'Shank_F_det'  % Shank3B females (WT/Het/KO), deterministic schedule
        C = struct( ...
            'dataFile',     'Shank3B_F_AB_D1.mat', ...
            'fitFile',      'FitModels_Shank_F_sess1.mat', ...
            'pEngagedFile', 'p_engaged_shank_F.mat', ...
            'models',       {MODELS_5}, ...
            'groupScheme',  'three', ...
            'pReward',      [], ...
            'pEngaged',     true, ...
            'indivSubplots', [8 5], ...
            'inequalityConstraints', false);

    case 'TSC_M_prob'   % Tsc2 males, probabilistic schedule
        C = struct( ...
            'dataFile',     'TSC2_pAB_D1.mat', ...
            'fitFile',      'FitModels_TSC_psess1.mat', ...
            'pEngagedFile', '', ...
            'models',       {MODELS_8}, ...
            'groupScheme',  'two', ...
            'pReward',      0.9, ...
            'pEngaged',     false, ...
            'indivSubplots', [6 5], ...
            'inequalityConstraints', true);

    case 'Shank_M_prob' % Shank3B males, probabilistic schedule
        C = struct( ...
            'dataFile',     'Shank3B_M_pAB_D1.mat', ...
            'fitFile',      'FitModels_Shank_psess1.mat', ...
            'pEngagedFile', 'p_engaged_shank_p.mat', ...
            'models',       {MODELS_5}, ...
            'groupScheme',  'two', ...
            'pReward',      0.9, ...
            'pEngaged',     true, ...
            'indivSubplots', [6 5], ...
            'inequalityConstraints', true);

    otherwise
        error('cohorts:unknownId', 'Unknown cohort id: %s', id);
end
C.id = id;
end
