function Ms = model_specs(names)
%MODEL_SPECS  Candidate model specifications for MAP fitting.
%
%   Ms = MODEL_SPECS(names) returns a 1xN cell array of model specification
%   structs for the models listed in NAMES (cell array of char), in the
%   given order. Each struct has fields:
%     name    - model name; the negative log-likelihood function is
%               [name '_llh'] in models/likelihood
%     pMin    - lower bounds of parameters
%     pMax    - upper bounds of parameters
%     pdfs    - cell array of parameter sampling functions used to draw
%               starting values for optimization
%     pnames  - parameter names
%
%   Models (see manuscript, "Computational Modeling" section):
%     RL_epsilon    standard RL: beta, alpha-, alpha+, stick, epsilon
%     a0b3s         alpha+ (alpha- fixed at 0), beta, stickiness s1-s3
%     a0b3s_hybrid  a0b3s + HMM mixture with biased policy (lapse, rec, bias)
%     a0b2s_hybrid  hybrid with s1, s2 (s3 = 0)
%     a0b1s_hybrid  hybrid with s1 only (s2 = s3 = 0); winning model
%     a01s_hybrid   hybrid without beta (beta fixed at 1)
%     Aab1s_hybrid  hybrid with free alpha- and alpha+
%     b1s_hybrid    hybrid with beta but no learning rate
%
%   Priors: the softmax inverse temperature beta has a normal prior with
%   mean 5 and SD 7 (added as a penalty to the negative log-likelihood in
%   FIT_MODELS); all other parameters have uninformative priors. Initial
%   parameter values are drawn from the sampling functions below.
%
%   See also COHORTS, FIT_MODELS.

%   Author: Jing-Jing Li (jl3676@berkeley.edu)

% Sampling functions for initial parameter values
beta_sample  = @(x) betarnd(5, 10);   % beta initial value ~ Beta(5, 10)
alpha_sample = @(x) unifrnd(0, 1);    % learning rate
stick_sample = @(x) unifrnd(-1, 1);   % stickiness
bias_sample  = @(x) unifrnd(0, 1);    % side bias
eps_sample   = @(x) unifrnd(0, 1);    % epsilon (uniform decision noise)
lapse_sample = @(x) unifrnd(0, 1);    % lapse probability  (T engaged->biased)
rec_sample   = @(x) unifrnd(0, 1);    % recover probability (T biased->engaged)

specs = struct();

specs.RL_epsilon = struct( ...
    'pMin', [1e-6 1e-6 1e-6 -1 1e-6], ...
    'pMax', [20 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, alpha_sample, stick_sample, eps_sample}}, ...
    'pnames', {{'beta', 'alpha-', 'alpha+', 'stick', 'epsilon'}});

specs.a0b3s = struct( ...
    'pMin', [1e-6 1e-6 -1 -1 -1], ...
    'pMax', [20 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, stick_sample, stick_sample, stick_sample}}, ...
    'pnames', {{'beta', 'alpha+', 's1', 's2', 's3'}});

specs.a0b3s_hybrid = struct( ...
    'pMin', [1e-6 1e-6 -1 -1 -1 1e-6 1e-6 1e-6], ...
    'pMax', [20 1 1 1 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, stick_sample, stick_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'beta', 'alpha+', 's1', 's2', 's3', 'lapse', 'rec', 'bias'}});

specs.a0b2s_hybrid = struct( ...
    'pMin', [1e-6 1e-6 -1 -1 1e-6 1e-6 1e-6], ...
    'pMax', [20 1 1 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, stick_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'beta', 'alpha+', 's1', 's2', 'lapse', 'rec', 'bias'}});

specs.a0b1s_hybrid = struct( ...
    'pMin', [1e-6 1e-6 -1 1e-6 1e-6 1e-6], ...
    'pMax', [20 1 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'beta', 'alpha+', 's1', 'lapse', 'rec', 'bias'}});

specs.a01s_hybrid = struct( ...
    'pMin', [1e-6 -1 1e-6 1e-6 1e-6], ...
    'pMax', [1 1 1 1 1], ...
    'pdfs', {{alpha_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'alpha+', 's1', 'lapse', 'rec', 'bias'}});

specs.Aab1s_hybrid = struct( ...
    'pMin', [1e-6 1e-6 1e-6 -1 1e-6 1e-6 1e-6], ...
    'pMax', [20 1 1 1 1 1 1], ...
    'pdfs', {{beta_sample, alpha_sample, alpha_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'beta', 'alpha-', 'alpha+', 's1', 'lapse', 'rec', 'bias'}});

specs.b1s_hybrid = struct( ...
    'pMin', [1e-6 -1 1e-6 1e-6 1e-6], ...
    'pMax', [20 1 1 1 1], ...
    'pdfs', {{beta_sample, stick_sample, lapse_sample, rec_sample, bias_sample}}, ...
    'pnames', {{'beta', 's1', 'lapse', 'rec', 'bias'}});

Ms = cell(1, numel(names));
for m = 1:numel(names)
    if ~isfield(specs, names{m})
        error('model_specs:unknownModel', 'Unknown model: %s', names{m});
    end
    s = specs.(names{m});
    s.name = names{m};
    Ms{m} = s;
end
end
